services:

# Database localhost
  mysql:
    hostname: plan-net.mysql
    container_name: plan-net.mysql
    image: mysql
    expose:
      - 3306
    ports:
      - '${APPLICATION_IP}:33063:3306'
    environment:
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

# plan-net project
  plan-net:
      build: image_setup/plan-net
      hostname: local.plan-net.ro
      container_name: plan-net
      image: plan-net
      links:
        - mysql
        - redis
      volumes:
        - '${LOCAL_APPS_DIR}/:/var/www/plan-net:delegated'
      ports:
        - '${APPLICATION_IP}:80:80'
        - '${APPLICATION_IP}:8888:8888'

  #memcached:
      #container_name: plan-net.memcached"
      #hostname: plan-net.memcached
      #image: memcached
      #ports:
        #- '${APPLICATION_IP}:11211:11211'
      #restart: on-failure:5

  redis:
      image: redis
      container_name: plan-net.redis
      restart: always
      ports:
        - '${APPLICATION_IP}:6379:6379'
      command: redis-server --save 20 1 --loglevel warning
      volumes:
        - cache:/data

volumes:
    cache:
      driver: local